export const DEFAULT_BOARD_COLOR = {
  black: "#1f1f1f",
  darkGray: "#8f8f8f",
  red: "#ff5a36",
  orange: "#ffa24c",
  yellow: "#ffc857",
  green: "#67d86f",
  teal: "#5ed7cf",
  blue: "#4db3ff",
  purple: "#8b52f6",
  pink: "#ec4ab8",
  white: "#ffffff",
  mediumGray: "#bdbdbd",
  lightGray: "#e5e7eb",
  lightRed: "#ffc2c2",
  lightOrange: "#ffe0bf",
  lightYellow: "#ffeab3",
  lightGreen: "#c8f0c8",
  lightTeal: "#c6f4ef",
  lightBlue: "#c8e7ff",
  lightPurple: "#d8c8ff",
  lightPink: "#f3b7df",
} as const;

export const DEFAULT_BOARD_COLORS = [
  DEFAULT_BOARD_COLOR.black,
  DEFAULT_BOARD_COLOR.darkGray,
  DEFAULT_BOARD_COLOR.red,
  DEFAULT_BOARD_COLOR.orange,
  DEFAULT_BOARD_COLOR.yellow,
  DEFAULT_BOARD_COLOR.green,
  DEFAULT_BOARD_COLOR.teal,
  DEFAULT_BOARD_COLOR.blue,
  DEFAULT_BOARD_COLOR.purple,
  DEFAULT_BOARD_COLOR.pink,
  DEFAULT_BOARD_COLOR.white,
  DEFAULT_BOARD_COLOR.mediumGray,
  DEFAULT_BOARD_COLOR.lightGray,
  DEFAULT_BOARD_COLOR.lightRed,
  DEFAULT_BOARD_COLOR.lightOrange,
  DEFAULT_BOARD_COLOR.lightYellow,
  DEFAULT_BOARD_COLOR.lightGreen,
  DEFAULT_BOARD_COLOR.lightTeal,
  DEFAULT_BOARD_COLOR.lightBlue,
  DEFAULT_BOARD_COLOR.lightPurple,
  DEFAULT_BOARD_COLOR.lightPink,
] as const;
