export const DEFAULT_PRESET_COLOR = {
  black: "#1f1f1f",
  darkGray: "#8f8f8f",
  red: "#ff5a36",
  orange: "#ffa24c",
  yellow: "#ffc857",
  green: "#67d86f",
  teal: "#5ed7cf",
  blue: "#4db3ff",
  purple: "#8b52f6",
  pink: "#ec4ab8",
  white: "#ffffff",
  mediumGray: "#bdbdbd",
  lightGray: "#e5e7eb",
  lightRed: "#ffc2c2",
  lightOrange: "#ffe0bf",
  lightYellow: "#ffeab3",
  lightGreen: "#c8f0c8",
  lightTeal: "#c6f4ef",
  lightBlue: "#c8e7ff",
  lightPurple: "#d8c8ff",
  lightPink: "#f3b7df",
} as const;

export const DEFAULT_PRESET_COLORS = [
  DEFAULT_PRESET_COLOR.black,
  DEFAULT_PRESET_COLOR.darkGray,
  DEFAULT_PRESET_COLOR.red,
  DEFAULT_PRESET_COLOR.orange,
  DEFAULT_PRESET_COLOR.yellow,
  DEFAULT_PRESET_COLOR.green,
  DEFAULT_PRESET_COLOR.teal,
  DEFAULT_PRESET_COLOR.blue,
  DEFAULT_PRESET_COLOR.purple,
  DEFAULT_PRESET_COLOR.pink,
  DEFAULT_PRESET_COLOR.white,
  DEFAULT_PRESET_COLOR.mediumGray,
  DEFAULT_PRESET_COLOR.lightGray,
  DEFAULT_PRESET_COLOR.lightRed,
  DEFAULT_PRESET_COLOR.lightOrange,
  DEFAULT_PRESET_COLOR.lightYellow,
  DEFAULT_PRESET_COLOR.lightGreen,
  DEFAULT_PRESET_COLOR.lightTeal,
  DEFAULT_PRESET_COLOR.lightBlue,
  DEFAULT_PRESET_COLOR.lightPurple,
  DEFAULT_PRESET_COLOR.lightPink,
] as const;
